### ISSUE TITLE
Create a product plan

### ISSUE THREAD

**Issue by meklenbpo** [kujunda-seda/Worthy-v2#1]
In order to start development of the app, we will need a **product plan**. Let's go and create one. 

I suggest starting with a basic list of requirements that we can further elaborate on. 
Let's create a new text document (e.g. product_requirements.txt) where we will accumulate what we plan to do.

It is probably a good idea to keep in mind the most basic first iteration and strip all the non-essential features at first.

**Comment by meklenbpo** [comment]
As discussed, it would be better to keep all project documentation (plans included) to the wiki, not cluttering the main folder.

**Comment by meklenbpo** [comment]
Also, let's base the product plan on the existing version 1. So, I would suggest filling out Worthy v.1 history in the wiki first, then proceed to the product plan.

**Comment by kalbaxa** [comment]
As feature list is ready we now need a roadmap. I suggest we research high-level implementation options and create a project architecture https://github.com/kujunda-seda/Worthy-v2/issues/24 first

**Comment by kalbaxa** [comment]
To sync up and return to product development I created a status.

We have:
- [Feature set](https://github.com/kujunda-seda/worthy-v2/blob/develop/documentation/product-work/feature-list-1.0.md)
- [All operations as performed by the user](https://github.com/kujunda-seda/worthy-v2/blob/develop/documentation/product-work/product-notes-accounting.md#types-of-entries)
- [How the operations and transactions will be stored](https://github.com/kujunda-seda/worthy-v2/blob/develop/documentation/product-work/product-notes-accounting.md)
- [Data that is required to be stored](https://github.com/kujunda-seda/worthy-v2/blob/develop/documentation/product-work/entity-structure.md)

We do not have:
- Roadmap for feature set 1.0 implementation
- Detailed user flow per feature
- Wireframes
- Mapping storage of entities into database
- API declaration
- Mock API

@meklenbpo
Is there anything I am missing?
Should we proceed in the order I mentioned?

**Comment by kalbaxa** [comment]
Done in #35
