### ISSUE TITLE
Move documentation from wiki to a folder

### ISSUE THREAD

**Issue by meklenbpo** [kujunda-seda/Worthy-v2#12]
# Goal: Move documentation from wiki to a folder in a repo
In order to be able to edit documentation locally it would be better to store the documentation as markdown files in a separate folder within the repo itself. Documentation related to the GitHub itself (project rules, git flow rules etc.) should stay in the wiki.

## Acceptance checklist:
- [x] create a folder structure within a repo where documentation files will be stored
- [x] move existing documentation entries from wiki to the newly created folder
- [x] amend project rules, clarifying which docs should be stored as files and which will remain in the wiki

**Comment by kalbaxa** [comment]
I didn’t amend project rules yet
